### ISSUE TITLE
Changing video orientation on the recorder needs to set the video orientation for all capture devices

### ISSUE THREAD

**Issue by mjgaylord** [rFlex/SCRecorder#104]
My app only records video in landscape orientation. So when I load the recorder, I load it in `LandscapeRight` by default.

When device orientation changes I perform the following:
```swift
    func updateRecorderOrientation() {
        if UIDevice.currentDevice().orientation == UIDeviceOrientation.LandscapeRight {
            recorder.videoOrientation = .LandscapeLeft
        } else if UIDevice.currentDevice().orientation == UIDeviceOrientation.LandscapeLeft {
            recorder.videoOrientation = .LandscapeRight
        }
    }
```

Rotation works 100% for the initial capture device. i.e. I can switch between orientations and the video updates correctly. But if the orientation is changed `LandscapeLeft` and I switch devices e.g. the front camera, the video is upside down.

The process seems to be consistent if I switch cameras from the front camera while in `LandscapeRight` orientation, then switch orientations and switch back to the back camera, the back camera is then upside down.

My only suspicion is that setting the video orientation on the recorder object, only sets the orientation on the active video capture device, and it most likely needs to be set on all devices, but I am unsure how to go about doing this.

**Comment by rFlex** [comment]
Have you tried setting "autoSetVideoOrientation" to YES?

**Comment by mjgaylord** [comment]
The problem with doing that is that then I need to allow the user to record in any orientation, which I would like to avoid, since I only want it to work in Landscape.

**Comment by mjgaylord** [comment]
Thanks for your help!

I've replicated the issue here: https://github.com/mjgaylord/SCRecorder/tree/broken-orientation

Basically the app is set to only have its orientation as Landscape Left. For now ignore that the controls don't rotate correctly, I left that out to save time.

`SCRecorderViewController` observes orientation notifications and flips the camera accordingly, but when you switch cameras the orientation is not being assigned. My logic might be a bit wrong, so the desired result is to be able to record in landscape only and ignore portrait orientations, but ensure that my video is always the correct "way up".

**Comment by rFlex** [comment]
Can you check on the last commit if the issue is fixed?

**Comment by mjgaylord** [comment]
Thanks. Checking now, will let you know...

**Comment by mjgaylord** [comment]
Yes, it works perfectly now! Thanks very much, this is awesome!
