### ISSUE TITLE
Way to generate "edit list"-free composition

### ISSUE THREAD

**Issue by jpswensen** [rFlex/SCRecorder#105]
I love how SCRecorder provides easy management of different segments. However, I think that because of how Apple generates MP4s from mutiple segments that it results in an MP4 that has edit lists that make is not play well with other video processing tools. 

We have been uploading our videos to a server and then trying to convert them to HTTP Live Streaming with ffmpeg. The problem is that it always complains about "multiple edit list entries, a/v desync might occur". I have confirmed that if the SCRecorder output is from a single segment that it doesn't have this characteristic. It only occurs when there are multiple segments.

I realize this is more of a problem of ffmpeg and the other tools that process these videos. However, do you know if there is a way to make the AVAssetExportSession for the AVMutableComposition *not* generate MP4s with these edit lists, but instead somehow just makes it like a single segment?

**Comment by mjgaylord** [comment]
We had the same problem. Record your videos to MOV with SCRecorder and then export to MP4. You will also need to have a low res version for your multiple bit rate file in order for playback to start instantly using HLS.

**Comment by mjgaylord** [comment]
One last thing. That warning can be ignored if your videos aren't actually going out of sync. But recording segments in mp4 and then merging them to mp4 causes audio sync issues, especially on longer videos.

**Comment by jpswensen** [comment]
Our audio sync problems occur when we try to change the frame rate. Apple recommends a set of encoding rates and frame rates in the HTTP Live Streaming guide. SCRecorder seems to be recording at 29.97 fps.

When you say record to MOV and then export to MP4, I tried recording to MOV (and verified with ffprobe), but I still see the "multiple edit list entries" warning from ffmpeg when converting to ts files at the various qualities before segmenting. The only way we can seem to prevent the audio sync issues when re-encoding at 10 fps, 15 fps, and 24 fps (all different than the native recording rate from our app) is to have ffmpeg do a "-vsync 0 -async 0" which in turn gives thousands of warnings like "Non-monotonous DTS in output stream". Also, we go from MOV/MP4 straight to a set of TS files at the recommended bit rates and then segment those files for HLS.

I really wish I was more of an encoding expert. I am kindof just flailing and hoping I find something that works.

**Comment by mjgaylord** [comment]
We are basically following the identical workflow as you, including the TS conversion from MP4, except we are leaving the framerates intact. Our videos stay in sync as long as the initial segments are recorded using MOV and not MP4. I am also not an ffmpeg or encoding expert unfortunately.

**Comment by mjgaylord** [comment]
Try testing with the Apple media segmenter tool. It might give you different results.

**Comment by jpswensen** [comment]
Were you able to hit the target bitrates with decent quality, while keeping the framerate intact?
We were trying to get the framerates and bitrates found in:
https://developer.apple.com/library/ios/technotes/tn2224/_index.html

I have messed around the the Apple media segmenter a little. However, we prefer our backend to be an EC2 instance running Linux.

**Comment by mjgaylord** [comment]
We didn't bother targeting the low bitrates. Since some of them are so low they aren't even used by AVPlayer and playback is super smoothe and starts almost instantaneously on very slow connections. You can inspect one of our m3u8 files here: https://storage.googleapis.com/storie-videos/HiJiGWLFkp/1420832606710.m3u8

**Comment by jpswensen** [comment]
Here is an example video that was recorded with SCRecorder (CocoaPod version 2.1.5).
https://s3-us-west-1.amazonaws.com/pichmesf/C177A949-EDE8-45B2-B193-885CFCF80CCC.mp4

Even though it says ".mp4", it is a ",mov", I just haven't got the S3 upload script fixed yet.

Even if I do something as simple as 
ffmpeg -i C177A949-EDE8-45B2-B193-885CFCF80CCC.mp4 C177A949-EDE8-45B2-B193-885CFCF80CCC_out.mp4
All the audio gets out of sync. It seems to get progressively worse the more starts and stops there are in the sequence that makes up the video. I can't figure out if it is a problem with ffmpeg not being able to handle the edit lists or if it is a problem with audio and video somehow being messed up in the segments from the video.

Our session setup is:
CGSize videoDimensions = CGSizeZero;
        videoDimensions.width = 480;
        videoDimensions.height = 480;
        
        
        NSDictionary* compressionProperties = @{AVVideoProfileLevelKey : AVVideoProfileLevelH264Baseline30, AVVideoAverageBitRateKey : @900000};
        
        NSDictionary *videoSettings = @{ AVVideoCodecKey : AVVideoCodecH264,
                                         AVVideoScalingModeKey : AVVideoScalingModeResizeAspectFill,
                                         AVVideoWidthKey : @(videoDimensions.width),
                                         AVVideoHeightKey : @(videoDimensions.height),
                                         AVVideoCompressionPropertiesKey : compressionProperties };
        _recordSession.videoOutputSettings = videoSettings;
        //_recordSession.fileType = AVFileTypeMPEG4;
        _recordSession.fileType = AVFileTypeQuickTimeMovie;
        
        _recorder = [SCRecorder recorder];
        _recorder.sessionPreset = AVCaptureSessionPreset1280x720;
        _recorder.audioEnabled = YES;
        _recorder.delegate = self;
        _recorder.autoSetVideoOrientation = YES;

Any thoughts?

**Comment by mjgaylord** [comment]
This is our setup, hopefully it helps:

```Swift
    private lazy var recorder: SCRecorder = {
        var recorder = SCRecorder()
        recorder.sessionPreset = self.highestPossiblePreset
        recorder.maxRecordDuration = CMTimeMakeWithSeconds(kRecordingLimitSeconds, 1)
        recorder.delegate = self
        recorder.frameRate = 30
        recorder.initializeRecordSessionLazily = true
        recorder.previewView = self.previewView
        
        //always make it landscape left, since the view controller is always opened in that orientation
        return recorder
    }()

    private lazy var recordSession: SCRecordSession = {
       var session = SCRecordSession()
        if let url = VideoSession.URLToTempDirectory {
            session.recordSegmentsDirectory = url
        }
        session.fileType = AVFileTypeQuickTimeMovie
        return session
    }()
```

And this is our export code:

```Swift
        var currentFilter = SCFilterGroup.filterGroupWithContentsOfURL(NSBundle.mainBundle().URLForResource("Plain", withExtension: "cisf"), groupName: "Standard")
        if let filter = filterSwitcherView.selectedFilterGroup {
            currentFilter = filter
        }
        var exportSession = SCAssetExportSession(asset: recordSession.assetRepresentingRecordSegments())
        exportSession.videoConfiguration.filterGroup = currentFilter
        exportSession.videoConfiguration.preset = SCPresetHighestQuality
        exportSession.audioConfiguration.preset = SCPresetMediumQuality
        exportSession.outputUrl = recordSession.outputUrl
        exportSession.outputFileType = AVFileTypeMPEG4
        exportSession.videoConfiguration.keepInputAffineTransform = true
        exportSession.exportAsynchronouslyWithCompletionHandler {
            let newURL = self.moveMergedVideoToDocuments(exportSession.outputUrl)
            completionHandler(newURL, exportSession.error)
        }
```

**Comment by rFlex** [comment]
I can't reproduce the bug on the sample even when using MP4 movie. My ffmpeg build:
`ffmpeg version 2.2.2 Copyright (c) 2000-2014 the FFmpeg developers
  built on May  9 2014 12:26:17 with Apple LLVM version 5.1 (clang-503.0.38) (based on LLVM 3.4svn)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/2.2.2 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-nonfree --enable-hardcoded-tables --enable-avresample --enable-vda --cc=clang --host-cflags= --host-ldflags= --enable-libx264 --enable-libfaac --enable-libmp3lame --enable-libxvid --enable-libfdk-aac`

Are you using libfdk-aac?

If you want to get rid of the "multiple edit list entries, a/v desync might occur" warning, you can use SCAssetExportSession instead of AVAssetExportSession (the latter is used by mergeRecordSegmentsUsingPreset:). SCAssetExportSession will reprocess every frame individually. The compression is slower, because it requires to decompress each input frame and compress it again. You can however have a precise output bitrate option, add a filter, watermark..
 I usually recommend to record the segments using a very high bitrate and then merge them into a file that has a  more suitable bitrate for the network using SCAssetExportSession.

What I tried to do on the sample:
- record several record segments with me talking (up to 20 seconds of video)
- save the video in the camera roll
- plug my phone and retrieve the file
- ffmpeg -i file.mp4 file_out.mp4
- open file_out.mp4

**Comment by jpswensen** [comment]
The SCAssetExportSession was the trick. Thanks to both of you. It got rid of both the edit list warnings and all the strange ffmpeg DTS warnings we were getting, and I don't see any of the audio sync problems anymore. The added processing time is perfectly acceptable as our videos are 30 seconds or less and we process the uploads and such in the background anyway. In case you are interested, we are close to a public beta release: http://www.pich.me/. One more thing off the list of sticky show stoppers.

Thanks!
