### ISSUE TITLE
switchcapturedevices ios7.1.2

### ISSUE THREAD

**Issue by hansaaaaa** [rFlex/SCRecorder#109]
Hi, I am running SCRecorder on my iphone4, iOS7.1.2, and have the following simple code for switching capture devices: 

- (void) handleReverseCameraTapped:(id)sender {
    [_recorder switchCaptureDevices];
}

This works on iPhone 5/6, but it doesn't work on my iphone4, ios7.1.2. I just get an empty black or white screen, i.e. back camera works, but front camera somehow doesn't. Does anyone have any advice for this? Thanks!

**Comment by mjgaylord** [comment]
This happened to me too. It's because the 4S doesn't support resolutions higher than 640x480 on the front camera.

**Comment by hansaaaaa** [comment]
Is there a way to set the resolution for SCRecorder programmatically, so I can work around this?

Thanks!

**Comment by rFlex** [comment]
Just change the sessionPreset on the SCRecorder.

https://developer.apple.com/library/mac/documentation/AVFoundation/Reference/AVCaptureSession_Class/index.html#//apple_ref/doc/constant_group/Video_Input_Presets

You can use +[SCRecorderTools bestSessionPresetCompatibleWithAllDevices] if you want to set the highest session preset that has the same resolution on both devices.
