### ISSUE TITLE
I see options (dictionary) in Photo Configuration class, what are other options can I provide?

### ISSUE THREAD

**Issue by thisdevguy** [rFlex/SCRecorder#119]
what are other options can I provide?

Thanks

**Comment by rFlex** [comment]
https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVCaptureStillImageOutput_Class/index.html#//apple_ref/occ/instp/AVCaptureStillImageOutput/outputSettings

Nothing really interesting for now unfortunately :(
