### ISSUE TITLE
Record Normally Not Tap

### ISSUE THREAD

**Issue by malik022** [rFlex/SCRecorder#121]
Is there a way to start the recording by just tapping the record button instead of holding it & on stop actually stopping the video?

**Comment by mjgaylord** [comment]
Yes you can. You can use the methods `record()` and `pause()` on the SCRecorder class. I can't seem to find where you can disable/enable tap-to-record, but if it you can't, just add a transparent view above the recorder and it should prevent taps from making their way to the recorder.

**Comment by malik022** [comment]
Can you post a code example of that @mjgaylord?

**Comment by mjgaylord** [comment]
In my case, I am using a gesture recognizer that is attached to a view that is above the SCRecorder to start and stop recording:
```swift
    func toggleRecord(gestureRecognizer: UITapGestureRecognizer) {
        if gestureRecognizer.state == UIGestureRecognizerState.Ended {
            if recorder.isRecording {
                recorder.pause()
            } else {
                recorder.record()
            }
        }
    }
```

**Comment by malik022** [comment]
@mjgaylord Could you post your xcode project? or drop me an e-mail with it.

**Comment by mjgaylord** [comment]
I can't give you my Xcode project unfortunately. But this should be very basic to accomplish. Try it with the sample project.

**Comment by malik022** [comment]
Which files should i edit in the sample project? @mjgaylord 
Thank you..

**Comment by rFlex** [comment]
SCRecorder doesn't provide any record button. You can use a UIButton and switch it between selected state when tapped then call [SCRecorder record] or [SCRecorder pause] depending on the UIButton's current state.
