### ISSUE TITLE
Podspec out of date.

### ISSUE THREAD

**Issue by jknightco** [rFlex/SCRecorder#126]
Hey there,

It looks like 2.2.4 is the latest version in Cocoapods (https://github.com/CocoaPods/Specs/tree/master/Specs/SCRecorder); would it be possible to update the podspec to a more recent version?

Thanks!

**Comment by rFlex** [comment]
Hey,

I'm going to update soon. Just finishing some stuff on the new_api branch. That will be ready this week :)

**Comment by jknightco** [comment]
Awesome! Thanks Simon. This project has saved tons of headaches and tons of
time—I really appreciate all your work on it.

**Comment by rFlex** [comment]
Just updated!
