### ISSUE TITLE
Broken on Pod Install

### ISSUE THREAD

**Issue by MMasterson** [rFlex/SCRecorder#129]
The line in  <s>SCImageHolder.h</s> CIImageRenderer.h
- (void)setImageBySampleBuffer:(CMSampleBufferRef)sampleBuffer;

gives error, "expect type"

iOS 8 xCode 6.1 - With a bridge header for Swift

**Comment by rFlex** [comment]
Hey,

I can't reproduce the issue. Can you share your project or tell a little more about how to reproduce it?

**Comment by MMasterson** [comment]
[platform :ios, '8.0'
use_frameworks!
pod "SCRecorder", ">= 2.3.0"]

**Comment by rFlex** [comment]
Can you update your pods and try again?

**Comment by MMasterson** [comment]
Installing SCRecorder 2.3.1 (was 2.3.0)

2.3.1 fixed the issue! Thank you very much! :+1:

**Comment by rFlex** [comment]
You are welcome! Thanks for reporting the issue!

**Comment by BhavinBhadani** [comment]
@rFlex  I am not able to update library through pods .. "[Bugfix - #263] Disable audio configuration if an out-going call exists" is not updated in my file
