### ISSUE TITLE
Video Output Size

### ISSUE THREAD

**Issue by 27deabril** [rFlex/SCRecorder#132]
I've been searching for a way to make my video "square". I noticed there is a property, inside SCVideoConfiguration, called sizeAsSquare, but I wasn't able to achieve this neither by setting it to true, nor by setting the size property to a square size.

I was also not able to produce the desired effect on the SCRecorderExamples project.

Am I missing something? Is there another property I should change so that sizeAsSquare will work? Would you be able to provide an example of what should be done to the SCRecorderExamples project so that it would work with squared outputs?

Thank you in advance!

**Comment by rFlex** [comment]
My bad, I forgot to remove "fastRecordMethodEnabled = YES" from the example. With this mode, it uses a different recording method that will skip most of the properties from SCVideoConfiguration. You can try it out now, it's working as expected ;).

**Comment by 27deabril** [comment]
Thank you a lot! I was able to make it work both in the SCRecorderExample and in my project.
