### ISSUE TITLE
Audio Offset (possibly avoidable - untested soultion)

### ISSUE THREAD

**Issue by MMasterson** [rFlex/SCRecorder#133]
While recording, if you choose to swap devices while in middle of a segment, there is an offset with the audio.

Now I'm just pulling the temp videos straight from the container for testing, I haven't fully exported the video - so once exported, it that may solve the issue

if not

another possible solution is
Forcing a segmentation when the camera is switch, - yet I haven't tried that either.

Finishing up for the night, will test tomorrow.

Any other thoughts on solving this issue? Or is the transition of swapping live too crude in general?

**Comment by rFlex** [comment]
I would personally force a segmentation. This would definitely solve the problem.

**Comment by MMasterson** [comment]
:+1:  Awesome, thought so! Didn't text yet, but closing the issue! Thanks again!
