### ISSUE TITLE
iPhone 4 video recording issue.

### ISSUE THREAD

**Issue by yarikpwnzer** [rFlex/SCRecorder#141]
Hello, thx for great library.

I found one issue when recording video with iphone 4 iOS 7.1.2 . It can be reproduced not always. While recording video output video file only contains Video or Audio Sample Buffer (method captureOutput:didOutputSampleBuffer:fromConnection). So in SCRecorder delegate method recorder:didCompleteSegment:inSession:error i got error = nil and segment = nil. Also i found while not recording with iphone 6 or 5s in method captureOutput:didOutputSampleBuffer:fromConnection i got next captureOutput:

- Video SampleBuffer Captured
- Audio SampleBuffer Captured
- Video SampleBuffer Captured
- Audio SampleBuffer Captured
- Video SampleBuffer Captured
- .........

same while recording.

With iphone 4 i have next sittuation:
Not recording:
- Video SampleBuffer Captured
- Video SampleBuffer Captured
- Video SampleBuffer Captured
- Video SampleBuffer Captured
- Video SampleBuffer Captured
- .....................
- Audio SampleBuffer Captured
- Audio SampleBuffer Captured
- Audio SampleBuffer Captured
- Audio SampleBuffer Captured
- Audio SampleBuffer Captured
- .....................

Again Video
and so on.

Recording :
- Audio SampleBuffer Captured
- Audio SampleBuffer Captured
- Audio SampleBuffer Captured
- Audio SampleBuffer Captured
- Audio SampleBuffer Captured
- Audio SampleBuffer Captured
- Audio SampleBuffer Captured
- .........................

Only Audio

Or

- Video SampleBuffer Captured
- Video SampleBuffer Captured
- Video SampleBuffer Captured
- Video SampleBuffer Captured
- Video SampleBuffer Captured
- Video SampleBuffer Captured
- ...........................

Only Video

I found similar issue here http://stackoverflow.com/questions/9257052/avcapturesession-only-got-video-buffer , but i dont know how to fix it. Please check.

**Comment by rFlex** [comment]
I highly recommend to use the "fastRecordMethodEnabled" property set to true on iPhone 4. It will enable you to record at a steady 30fps (at the cost of not being able to set the bitrate, video size and various other settings at the recording time).

**Comment by yarikpwnzer** [comment]
@rFlex yeah, really works well. Should i also set this property to true on other devices?

**Comment by chdtyzhy** [comment]
You and I have the same problem, and now you solve?

**Comment by yarikpwnzer** [comment]
@chdtyzhy Yes, "fastRecordMethodEnabled"=YES solve my problem.

Also i'm closing this ticket.

**Comment by chdtyzhy** [comment]
@yarikpwnzer   how  to sett  fastRecordMethodEnabled=YES, I just can't found the property

**Comment by yarikpwnzer** [comment]
@chdtyzhy Firstly update SCRecorder library and than you could find fastRecordMethodEnabled property in SCRecorder class.

**Comment by chdtyzhy** [comment]
I have a try

**Comment by mrugeshtank** [comment]
I am recording video at 30fps via AVFoundation. and getting this problem.
How can I solve them?
