### ISSUE TITLE
Crash due to potential memory leak when recording multiple videos in a row

### ISSUE THREAD

**Issue by mjgaylord** [rFlex/SCRecorder#142]
If you record multiple clips using the SCRecorderExamples app and save them to the camera roll, after about 5-7 tries on an iPhone 6+ the app crashes. I think this is memory related, since the app gets issued a `Killed: 9` and doesn't stop on a breakpoint in the debugger. I can also see a whole bunch of low memory warnings in the device logs just before it happens.

```Apr  3 17:41:38 iPhone com.apple.xpc.launchd[1] (UIKitApplication:me.corsin.SCRecorderExamples[0x57d2][16420]) <Notice>: Service exited due to signal: Killed: 9```

Further down the device logs:

```Apr  3 17:41:38 iPhone SpringBoard[53] <Warning>: Application 'UIKitApplication:me.corsin.SCRecorderExamples[0x57d2]' exited abnormally via signal.```

Sometimes I do see the following, but I am not sure if it is related:

```Apr  3 17:37:57 iPhone discoveryd[14857] <Notice>: Basic DeviceInformation Memory Pressure Warning sent: pressure```

We are experiencing the same behaviour in our app too, so I don't think this issue is isolated to the example project.

If you need more info, let me know.

**Comment by rFlex** [comment]
Hey Michael,

I believe this issue has been fixed on the last commit. SCPlayer instances and its attached CIImageRenderer would not be deallocated if you didn't unset the CIImageRenderer property. The latest version doesn't require you to unset that property.

**Comment by mjgaylord** [comment]
Ok awesome, thanks for taking a look at it. I just pulled the latest code to test, but I can't run the Objc example, I get this error:

/SCRecorder/Examples/ObjC/Sources/SCAudioRecordViewController.h:10:9: 'SCRecorder/SCRecorder.h' file not found

**Comment by mjgaylord** [comment]
In my own tests, this appears to have been resolved.

**Comment by rFlex** [comment]
The example doesn't compile?

**Comment by mjgaylord** [comment]
Sorry, meant to clarify it is a compilation issue. I even deleted and re-cloned the entire repository and it still gave me the error.
