### ISSUE TITLE
use "a_filter.cisf" will be crash in iOS SCRecorderExamples 

### ISSUE THREAD

**Issue by BensonZhu** [rFlex/SCRecorder#145]
use "a_filter.cisf" will be creash in iOS SCRecorderExamples ,

        self.filterSwitcherView.filters = @[
                                                 [SCFilter emptyFilter],
                                                 [SCFilter filterWithCIFilterName:@"CIPhotoEffectNoir"],
                                                 [SCFilter filterWithCIFilterName:@"CIPhotoEffectChrome"],
                                                 [SCFilter filterWithCIFilterName:@"CIPhotoEffectInstant"],
                                                 [SCFilter filterWithCIFilterName:@"CIPhotoEffectTonal"],
                                                 [SCFilter filterWithCIFilterName:@"CIPhotoEffectFade"],
                                                 // Adding a filter created using CoreImageShop
                                                 [SCFilter filterWithContentsOfURL:[[NSBundle mainBundle] URLForResource:@"a_filter" withExtension:@"cisf"]]
                                                 ];

it is  return a nil  object.

**Comment by rFlex** [comment]
The a_filter file has been generated with an old version of CoreImageShop. I haven't taken the time to change it yet.
