### ISSUE TITLE
Adding watermark

### ISSUE THREAD

**Issue by aabanaag** [rFlex/SCRecorder#149]
I would like to add the current date and running time as watermark for the video. But currently watermark is only set to UIImage. Will it be possible to append watermark as text instead of image?

**Comment by rFlex** [comment]
You need to draw an UIImage yourself. There is so many way you could want to set your watermark. The only generic way is to use an image. You can create a UILabel, set the font and the text you want, create an image context and render the layer of that UILabel in it.

**Comment by aabanaag** [comment]
But what I want to achieve is to have a timestamp where the watermark itself is a running timer or clock from where the video started recording. So drawing an UIImage would be too expensive plus it would happen at the end. where a timestamp should be added per frame I think
