### ISSUE TITLE
Any chance to get ios 8 version ?

### ISSUE THREAD

**Issue by meandkareem** [rFlex/SCRecorder#150]
any chance to get this working on ios 8? 

videoMaxFrameDuration
isVideoMaxFrameDurationSupported
enablesVideoStabilizationWhenAvailable
... deprecated

**Comment by scottrhoyt** [comment]
I made the necessary changes here:

https://github.com/scottrhoyt/SCRecorder/

I'll submit a pull request, but by the looks of the code, the author appears well aware of the new methods for iOS 7/8 and is choosing to keep backwards compatibility. He may choose to suppress the warnings individually in the future.

**Comment by rFlex** [comment]
They all work correctly, you can safely ignore the warnings. I just pushed a commit that removes them anyway.
