### ISSUE TITLE
when  SCRecorderViewController pop  the demo crash

### ISSUE THREAD

**Issue by pathfinder1989** [rFlex/SCRecorder#151]
when  SCRecorderViewController pop  the demo crash

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x146620f40 of class SCRecorder was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x170053a70> (
<NSKeyValueObservance 0x1700d9280: Observer: 0x14662a2d0, Key path: isAdjustingFocus, Options: <New: YES, Old: NO, Prior: NO> Context: 0x1001030fc, Property: 0x170053aa0>
)'

in the SCRecorderToolsView class implement  when SCRecorderViewController pop
[oldRecorder removeObserver:self forKeyPath:@"isAdjustingFocus"];  can not call

**Comment by rFlex** [comment]
Fixed

**Comment by elirane** [comment]
What is the file you have fixed?
