### ISSUE TITLE
Small edge in "SCSwipeableFilterView"

### ISSUE THREAD

**Issue by xportation** [rFlex/SCRecorder#152]
I can't remove a small edge in SCSwipeableFilterView.
This happen both in your example as in my project.

To simulate you must to record a movie and apply filters in the preview. Look for a white line in the right of the screen.

![image](https://cloud.githubusercontent.com/assets/4412615/7383801/03d0ae70-edfc-11e4-8288-22ff80f97383.png)

I'm trying to solve this, but maybe you can do this faster.

Thanks

**Comment by rFlex** [comment]
Hey,

Just set UIViewContentModeScaleAspectFill to the contentMode property of your SCSwipeableFilterView instance.

**Comment by dimohamdy** [comment]
not fixed
