### ISSUE TITLE
How to save the recorded video file, not to the asset library?

### ISSUE THREAD

**Issue by ArkadiYoskovitz** [rFlex/SCRecorder#155]
Been looking for a way to save the file to disk but it keeps giving me a url to a resource that dent exists.

I'm trying to implement a web protocol for file upload but  can't seem to get the real file url from the framework

Also is there a way to convert the video record into a NSData object?

**Comment by rFlex** [comment]
SCRecorder always saves to the disk no matter what. Can you explain in more details what you are doing and what you are expecting.

To have the whole video as NSData, just use +[NSData dataWithContentsOfURL:].

**Comment by ArkadiYoskovitz** [comment]
I do a merge and then try to load

**Comment by ArkadiYoskovitz** [comment]
Damn web device....

I do a merge and the I wand to load the merged file to nsdata but I keep getting a file not found then reading from the output url

**Comment by rFlex** [comment]
Can you share the relevant code you are using?

**Comment by ArkadiYoskovitz** [comment]
Turned out to be a misplaced __block declaration
