### ISSUE TITLE
Watermark image gets Filter Applied to It

### ISSUE THREAD

**Issue by zoruc** [rFlex/SCRecorder#156]
Hey rFlex,
Is there a way to choose whether the watermarked image gets a filter applied to it or not, currently i'm not finding it and it just filters over the watermark and that can lead to a non desired effect sometimes.  
Thanks
Zoruc

**Comment by rFlex** [comment]
The solution would be to implement the watermark using a filter. Let me
some time to change that ;).

**Comment by rFlex** [comment]
I just pushed a new commit. Can you check if that works fine for you?

**Comment by zoruc** [comment]
Works perfectly thanks alot
