### ISSUE TITLE
SCRecorder interface builder support

### ISSUE THREAD

**Issue by ArkadiYoskovitz** [rFlex/SCRecorder#157]
Some of the SCRecorder library classes are meant to be used with interface builder, such as the SCVideoPlayerView, they should expose IBOutlets for things that are usually set in interface builder, like the delegate property and such.

**Comment by rFlex** [comment]
Just pushed. Did you find anything else that the delegate of SCVideoPlayerView?

**Comment by ArkadiYoskovitz** [comment]
That was the only think that really bugged me about the current library version.

Frankly its a question of what you want to do.

Personally i think that going IB_Designable is a good idea, which means that everything that has to do with UI classes should be exposed but you might not want to do that if you wand a backward support.

**Comment by rFlex** [comment]
Thanks for the idea ;)
