### ISSUE TITLE
Deprecated warning for iOS 8 in SCRecorder.m

### ISSUE THREAD

**Issue by scottrhoyt** [rFlex/SCRecorder#158]
The use of `enablesVideoStabilizationWhenAvailable` triggers a deprecation warning in iOS 8. It is referenced in SCRecorder.m in the method `configureDevice:mediaType:error:`.

![screen shot 2015-05-08 at 9 55 08 am](https://cloud.githubusercontent.com/assets/4259250/7541272/bb91e8a8-f568-11e4-8f61-e07c95e82826.png)

**Comment by rFlex** [comment]
Fixed ;)

**Comment by rFlex** [comment]
Fixed ;)

**Comment by scottrhoyt** [comment]
Thanks!
