### ISSUE TITLE
SCPlayer - Progress indicator

### ISSUE THREAD

**Issue by ArkadiYoskovitz** [rFlex/SCRecorder#159]
Hi,

I'm trying to make the player provide a  playback progress but, it's not clear from the API how it's possible, if at all. any advice on the matter will be welcome.

**Comment by Xcoder89** [comment]
@rFlex would be able to give the exact solution but here's how I do it;
Set the player delegate ( player.delegate = self ) and then  [player beginSendingPlayMessages]
Then you will have this this delegate called
- (void)player:(SCPlayer*)player didPlay:(CMTime)currentTime loopsCount:(NSInteger)loopsCount{
      Float64 seconds = CMTimeGetSeconds(currentTime);
}

**Comment by rFlex** [comment]
@xcoder89 is correct ;)

**Comment by ArkadiYoskovitz** [comment]
Hi,

@Xcoder89 thanks for the tip. it worked for me.

@rFlex its really unclear from the API and the documentation, please add it somewhere I'm guessing that there are more people with the same problem

**Comment by ArkadiYoskovitz** [comment]
And again thank you both for the help
