### ISSUE TITLE
Issue when saving videos

### ISSUE THREAD

**Issue by Jensen2k** [rFlex/SCRecorder#16]
Hey, thanks for the great library. We are using it in something really cool, and i can't wait to show you!

So, to the problem at hand.
When i'm using the exact same code as the example on iOS, i often encounter a writing error on the AVAssetWriter in SCAudioVideoRecorder.m

```
*** Terminating app due to uncaught exception 
'NSInternalInconsistencyException', reason: 
'*** -[AVAssetWriter finishWritingWithCompletionHandler:] 
Cannot call method when status is 1'
```

The error occurs on line 266:

```
- (void) finishWriter:(NSURL*)fileUrl {
#if TARGET_IPHONE_SIMULATOR || TARGET_OS_IPHONE
    [self.assetWriter finishWritingWithCompletionHandler:^ { // <-- Here
        dispatch_async(self.dispatch_queue, ^{
            [self stopInternal];
        });
    }];
```

Hope that you can help with this!

**Comment by zackhsuan** [comment]
Sorry to dig this issue out... but @rFlex I have encountered this issue a lot in my personal project. Which is the "[AVAssetWriter finishWritingWithCompletionHandler:] Cannot call method when status is 1" crash. Wondering if you have found out what possible reasons caused this error, could you please kindly share me some fixes?
