### ISSUE TITLE
Bug: If you save a video without at least swiping once, it's a black screen with voice

### ISSUE THREAD

**Issue by Knights22** [rFlex/SCRecorder#167]
After recording a video, if you just save it without swiping over the filters, it will save a black screen with just the audio. I am guessing something only gets initialized after the first swipe, because if i swipe back to the video with no filter it will save correctly.

**Comment by sebyddd** [comment]
Still having this issue.

**Comment by sebyddd** [comment]
Solved it by removing the watermark. Can please update the demo project?

Thanks!
