### ISSUE TITLE
Swift Crash on exportAsynchronouslyWithCompletionHandler

### ISSUE THREAD

**Issue by huntermonk** [rFlex/SCRecorder#168]
Hi,

When calling the exportAsynchronouslyWithCompletionHandler method on an SCAssetExportSession in the swift environment, I get a crash on line 418 of SCAssetExportSession.m. Line 418 is the first line here:

```javascript
if (![_reader startReading]) {
        EnsureSuccess(_reader.error, completionHandler);
    }
```

I'm able to export using a standard AVAssetExportSession using the same asset, outputURL etc., so I'm just guessing it's a problem with running it in swift, since the example project (in obj-C) exports just fine.

Here's example code that creates the crash:

```javascript
seg.getDataInBackgroundWithBlock({
      (data, error) -> Void in
       let tmpDirURL = NSURL(fileURLWithPath: NSTemporaryDirectory(), isDirectory: true)!
       let fileURL = tmpDirURL.URLByAppendingPathComponent("temp\(arc4random())")
       let newFileURL = fileURL.URLByAppendingPathExtension("mp4")
       let urlData:NSData = data!
       urlData.writeToURL(newFileURL, options: NSDataWritingOptions.AtomicWrite, error: nil)
                    
       let session = SCRecordSession()
                    
       session.addSegment(SCRecordSessionSegment(URL: newFileURL, info: nil))
                    
       let asset = session.assetRepresentingSegments()
                    
       let SCSession = SCAssetExportSession(asset: asset)
       SCSession.videoConfiguration.preset = SCPresetHighestQuality
       SCSession.audioConfiguration.preset = SCPresetHighestQuality
       SCSession.videoConfiguration.maxFrameRate = 35
       SCSession.outputFileType = AVFileTypeMPEG4
       SCSession.outputUrl = newFileURL
       SCSession.delegate = self

       SCSession.exportAsynchronouslyWithCompletionHandler({
            println("SCAsset exported")
       })             
                    
})
```

Thanks.

**Comment by rFlex** [comment]
Hey,

What's the exception that gets thrown? Also, are you calling exportAsynchronouslyWithCompletionHandler in the main thread? I'm not certain it would work correctly if you don't. Keep in mind that all the heavy process in done in a separate queue anyway, so setting up the SCAssetExportSession and starting it in the main queue is not a big deal.

Thanks ;)

**Comment by praveenaj** [comment]
I'm running into the same issue. But I'm on Obj-C. Example works fine, but not in my adapted code. Debugger stops at ```if (![_reader startReading]) {``` with no error.

**Comment by yarikpwnzer** [comment]
Same issue in Obj-C. Running on main thread.

**Comment by huntermonk** [comment]
Hey just got this figured out - I had a breakpoint on for all exceptions. I disabled the breakpoint and am now able to export just fine. 

@praveenaj and @yarikpwnzer do you have all exceptions breakpoint turned on?

**Comment by praveenaj** [comment]
@huntermonk Yes! You're right. I disabled the breakpoint and now it's working! Thanks a lot. :+1:  But I wonder why the exception is thrown. Something isn't right somewhere.

**Comment by huntermonk** [comment]
Haha ok awesome. Yeah I would like to be able to still build with all exceptions break on, @rFlex let me know if there's any way I can help to stop that exception from being thrown.

**Comment by yarikpwnzer** [comment]
@huntermonk @praveenaj Yes it throws exception only with all exceptions break on. I forgot to mention it.

**Comment by rFlex** [comment]
Yes it's not that it crashes, it's just that there is a C++ exception that get thrown somewhere in Apple's code. I'm not sure I can do something about that. Just configure xcode to stop on objective-c exception only.

**Comment by praveenaj** [comment]
@rFlex Sure. That's fine. Thanks for the awesome library! :clap:

**Comment by rFlex** [comment]
Thanks :)
