### ISSUE TITLE
Exporting with filter causes skips

### ISSUE THREAD

**Issue by huntermonk** [rFlex/SCRecorder#176]
If a filter is applied to an SCAssetExportSession, the exported asset often has skips in it. [Here's a link to an example.](https://www.dropbox.com/s/yw8oxtx0oc5li7r/2015-06-15%2015.28.05.mov?dl=0) You'll notice skipped frames in the middle and (although it's hard to see in this video) at the end. 

I'm running the example project on an iPhone 5S.

Oddly enough, if you export in the same exact same way and don't have a filter selected (or even if you have an empty SCFilter selected), those skipped frames never seem to happen.

**Comment by huntermonk** [comment]
The skipping seems to only happen when the SCAssetExportSession videoConfig filter is being set by the filterSwitcherView (using currentFilter).

If I directly set the filter of the export session, I can't seem to produce any skips.

**Comment by rFlex** [comment]
I added the NSCopying support in SCFilter. You can set the selectedFilter to SCAssetExportSession by copying it. SCFilter isn't thread safe, so if you put the same instance on a player and an exporter and that they both use it at the same time, you may encounter some problem : )

**Comment by huntermonk** [comment]
Ah ok that makes sense, thanks for adding that!
