### ISSUE TITLE
mergeSegmentsUsingPreset AVFoundationErrorDomain Code=-11800 "The operation could not be completed"

### ISSUE THREAD

**Issue by jjeon5** [rFlex/SCRecorder#179]
I am capturing video using standard AVFoundation, and have an array of urls to the videos. I've checked that the videos are playable. I then create `SCRecordSessionSegment` using those `NSURL`s. However when I add the segments to a `SCRecordSession`, and try to merge the videos, it throws me these errors. Is this the right way to merge non-SCRecord outputted videos using mergeSegmentsUsingPreset? Am I missing something? Thanks.

```
Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed"
 UserInfo=0x170a7ac00 {NSUnderlyingError=0x17404a1d0 "The operation couldn’t be completed. (OSStatus error 1852797029.)",
 NSLocalizedFailureReason=An unknown error occurred (1852797029), NSLocalizedDescription=The operation could not be completed}
```

Here is the code.

```
var recordSession = SCRecordSession()
recordSession.addSegment(SCRecordSessionSegment(URL: videoUrl1, info: nil))
recordSession.addSegment(SCRecordSessionSegment(URL: videoUrl2, info: nil))
recordSession.fileType = AVFileTypeQuickTimeMovie
recordSession.mergeSegmentsUsingPreset(AVAssetExportPreset1280x720, completionHandler: { (url, error) -> Void in
   if error == nil {
         self.playVideo(url)
    } else {
        print(error)
    }
})
```

**Comment by justinmakaila** [comment]
This is purely speculation, because I'm not terribly familiar with the internals, but I believe this could be a timestamp issue. `AVFoundation` has a difficult time trying to infer timestamps.

**Comment by Drusy** [comment]
I can't resolve your problem, but just in case it could be useful, check this website http://www.osstatus.com/ to get more details about your OSStatus errors.
