### ISSUE TITLE
not start recoding again once get following error

### ISSUE THREAD

**Issue by jydpptl** [rFlex/SCRecorder#183]
Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo=0x17467ce80 {NSUnderlyingError=0x174458030 "The operation couldn’t be completed. (OSStatus error -12983.)", NSLocalizedFailureReason=An unknown error occurred (-12983), NSLocalizedDescription=The operation could not be completed

[writer startWriting] is not start after that

**Comment by yarikpwnzer** [comment]
Some clients of my app have same error. I set maxFrameRate to 35. I don't know if it helps, since i can't reproduce on my devices.

**Comment by jydpptl** [comment]
in my case it is not working :(

**Comment by yarikpwnzer** [comment]
@jydpptl maybe you haven't enough free space on device?

**Comment by jydpptl** [comment]
Thank you @yarikpwnzer for your suggestions & help :)
I solve this issue using remove SCRecorderToolsView object from its super view on viewWillDisappear 
now its work fine for me after that.
