### ISSUE TITLE
Easy SCImageView Implementation resulting in black screen Swift

### ISSUE THREAD

**Issue by jeon97** [rFlex/SCRecorder#189]
Really simple implementation using your tutorial results in a black screen. 

```
self.moviePlayer = SCPlayer()
self.moviePlayer.setItemByAsset(recordSession.assetRepresentingSegments())
var playerLayer = AVPlayerLayer(player: moviePlayer)
playerLayer.frame.origin = CGPoint(x: 0,y: 0)
playerLayer.frame.size = self.mainview.frame.size
self.mainview.layer.addSublayer(playerLayer)
moviePlayer.loopEnabled = true
moviePlayer.play()
```
This works perfectly fine but once I add 
```
var a = SCImageView(frame: CGRect(origin: CGPoint(x: 0, y: 0), size: self.mainview.frame.size))
a.filter = SCFilter(CIFilter: CIFilter(name: "CIPhotoEffectInstant"))
moviePlayer.CIImageRenderer = a
self.mainview.addSubview(a)
```
the mainview turns black.
Any Idea?

**Comment by jeon97** [comment]
Also, the AVVideoPlayerView way just plainly doesn't work.

**Comment by Sneakr** [comment]
You are putting a SCImageView on top of moviePlayer, and the SCImageView gets your filter input (a.filter) but nothing to render the filter on, so the result is a black screen.

**Comment by jeon97** [comment]
so how do i fix it?

**Comment by Sneakr** [comment]
Did you try with SCVideoPlayerView to render the filters through SCImageView as the tutorial suggest?

**Comment by jeon97** [comment]
Yes, SCVideoPlayerView isn't working for me even without the filter. I meant SCVideoPlayerView in my comment that says AVVideoPlayerView

**Comment by jeon97** [comment]
I used this code for the SCVideoPlayerView path
```
var playerView = SCVideoPlayerView(frame: CGRect(x: 0, y: 50, width: UIScreen.mainScreen().bounds.width, height: UIScreen.mainScreen().bounds.width))
        self.view.addSubview(playerView)
        self.moviePlayer = playerView.player
        playerView.player?.setItemByAsset(recordSession.assetRepresentingSegments())
        playerView.player?.loopEnabled = true
        playerView.player?.play()
```
This results in the playerView not being seen.
In the view hierarchy debugger it shows the playerView as an empty SCVideoPlayerView

**Comment by Sneakr** [comment]
Im relative new to coding, but since the code is working perfectly well, I think the mess up is either in your views set up or , as I can think of now (and like I did before), there is no input to render,

it's hard to figure out since I cant see the viewcontrollers, but --> 

with the small information I have, did you prepare the recordSession  in prepareforsegue in the RecordViewcontroller before going into the PlayerViewcontroller after recording finished?

Because if you didnt, this will result in black screen with nothign to render since there are no sessions loaded. :)

**Comment by jeon97** [comment]
the sessions are definitely loaded because the scplayer + scplayer layer path shows the video perfectly. It's just that when I try to add the filter ( the 4 lines of code in my initial question) nothing is shown.

**Comment by Sneakr** [comment]
Yes, but if you try to export when nothing is shown, with a filter line on,

and you can see if the filter is processed in the export or not, or if you even get any video at all.

then you can localize where the error occurs easier.

**Comment by jeon97** [comment]
Yep it is exported nicely. However I'm seeing that the moviePlayer is nil. I thought the mySCPlayerView.player is already initialized, judging from the tutorial. Do I have to initialize a SCPlayer myself and set it to mySCPlayerView.player?

**Comment by Sneakr** [comment]
Cool, then it is only the matter of views setup. My experience/knowledge has reached its limits now sorry :P

 but  if you check the example project I think you can get the hints, I just followed the example project and had no problem setting up anything, but I use storyboard and set up the "renderer/player" VIEW and set its class in storyboard to SCSwipeableFilterView and connect the view with property: 

@property (weak, nonatomic) IBOutlet SCSwipeableFilterView *filterSwitcherView;

then just in my .m I do _player.CIImageRenderer = self.(myrendererview)

I do the exact same thing with SCImageView, and it should work for you if you set up the views correctly.

**Comment by jeon97** [comment]
Alright. I'll look more into it. Thanks a lot!!

**Comment by khush004** [comment]
@jjeon5 Did you solved this?
