### ISSUE TITLE
SCRecorder © Watermark Label

### ISSUE THREAD

**Issue by aqibmumtaz** [rFlex/SCRecorder#190]
Hi there,

For each video created by SCRecorder Example project saved to camera roll has watermark showing "SCRecorder ©" on bottom right corner, Can we remove this watermark as we are planning to use this lib in our commercial iOS FREE product?

Thanks,

**Comment by rFlex** [comment]
The watermark is added programmatically on the example. I suppose you
copy pasted that code without removing this part?

**Comment by aqibmumtaz** [comment]
OK thanks, I ll remove it from code.
