### ISSUE TITLE
SCVideoPlayerViewController preview not smooth

### ISSUE THREAD

**Issue by wojczitsu** [rFlex/SCRecorder#191]
When I run example project on iPad mini 1st gen (iOS 9.0), preview screen with SCSwipeableFilterView is not playing video smoothly, there's really big lag, while audio from video is playing ok. Is there a way too make it run smoothly with filters preview?

**Comment by wojczitsu** [comment]
iPad Mini: not smooth
iPad 2: OK
iPhone 4: not smooth
iPhone 5s: OK

**Comment by NileshKalathiya** [comment]
Hello @wojczitsu, Did you got any solution?
