### ISSUE TITLE
Apply SCFilter into live recording

### ISSUE THREAD

**Issue by ustbenchan** [rFlex/SCRecorder#198]
Thank you for this module.

I would like to ask how I can directly apply scfilter into live recording

This is how I setup:
```swift

//recorder.previewView = self.previewView // do not set the previewView
recorder.CIImageRenderer = self.scImageView

let filter = SCFilter(CIFilterName: "CIColorControls")
filter.setParameterValue(NSNumber(float: 0.3), forKey: "inputContrast")

self.scImageView.filter = filter

```

It runs without problem, but the scImageView does not output any frame
I have checked the codes inside SCImageView, it calls the 
```Objective-c
- (void)setImageBySampleBuffer:(CMSampleBufferRef)sampleBuffer
```
but the
```Objective-c
- (void)drawRect:(CGRect)rect
```
is never called

Do you have ideas on why it happens?

**Comment by ustbenchan** [comment]
It seems #182 has this problem covered

**Comment by xportation** [comment]
I’m using a SCSwipeableFilterView widget. My setup is:
```objective-c
self.filterSwitcherView.refreshAutomaticallyWhenScrolling = FALSE;
self.filterSwitcherView.contentMode = UIViewContentModeScaleAspectFill;
        
self.filterSwitcherView.filters = @[
                                            [SCFilter emptyFilter],,
                                            [SCFilter filterWithCIFilterName:@"CIPhotoEffectInstant"],
                                            [SCFilter filterWithCIFilterName:@"CIPhotoEffectTonal"]
                                            ];
recorder.CIImageRenderer = self.filterSwitcherView;
```
This is not working good, it’s slow. Looks a delay while rendering. I don’t know what’s happening.

**Comment by xezero** [comment]
@ustbenchan See my solution in #182.

**Comment by fayhot** [comment]
@ustbenchan 

So sorry that i just see this. That's a terrible hack.

A better way is just like what @xezero  said.

And I solve it with a similar way.
