### ISSUE TITLE
Disorder of SCWatermarkOverlayView color space

### ISSUE THREAD

**Issue by xhzengAIB** [rFlex/SCRecorder#199]
Hi! @rFlex 
Long time no contact.

I add subview in SCWatermarkOverlayView initWithFrame function.
```objc
        UIView *view = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 100, 100)];
        view.backgroundColor = [UIColor redColor];
        [self addSubview:view];
```

But the redColor will be change like blueColor,  maybe add UIImageVIew to SCWatermarkOverlayView will be change the image color space.

I guess is a problem of color space, this due with function:
https://github.com/rFlex/SCRecorder/blob/master/Library/Sources/SCAssetExportSession.m#L146

and this line:
https://github.com/rFlex/SCRecorder/blob/master/Library/Sources/SCAssetExportSession.m#L155

Change color picture:
![d6ae7798-54b3-4bbd-9f26-313c88d15035](https://cloud.githubusercontent.com/assets/1969908/9350809/49edbbb8-4686-11e5-819f-074e6818e8e0.png)

**Comment by twomedia** [comment]
I am also eager to find a solution to this issue, I am trying to overlay text+emojis and am finding that on export the emojis colours are slightly different.

**Comment by xhzengAIB** [comment]
Hi！@twomedia 

How to solve?

Jack

**Comment by twomedia** [comment]
Haven't found a solution yet @xhzengAIB :(

**Comment by fuchen2624** [comment]
solve~
http://stackoverflow.com/questions/9920836/color-distortion-in-cgimagecreate

**Comment by twomedia** [comment]
Thank You @fuchen2624! That fixed it! You're a legend mate! :D

**Comment by rFlex** [comment]
Merged #207 
Can you confirm the issue is fixed?

**Comment by twomedia** [comment]
@rFlex I can confirm this is fixed, colors are now rendering correctly.

**Comment by xhzengAIB** [comment]
Thanks @twomedia @rFlex
