### ISSUE TITLE
Recording square video

### ISSUE THREAD

**Issue by sethroot** [rFlex/SCRecorder#20]
I'm having trouble configuring the recorder to capture and export video cropped to a square aspect ratio. Without expertise in AVFoundation I am having a hard time understanding whether this is currently possible to do. Is this currently a supported feature for iOS?

I can see that Issue #1 relates to this question but it was closed 7 months ago and the codebase has changed since that resolution. Specifically, it seems that the functionality associated with useInputFormatTypeAsOutputType has been rewritten.

I have tried to configure the recorder using the following methods without success:
- camera.videoEncoder.outputVideoSize
- camera.sessionPreset
- [camera setActiveFormatThatSupportsFrameRate:width:andHeight:error:]

Any information on this matter would be greatly appreciated.

**Comment by cerupcat** [comment]
@rFlex do you know where I'd look if I wanted to try cropping the video from the top instead of the center?

**Comment by joshoconnor89** [comment]
#324
