### ISSUE TITLE
What's going on here? Anyone home??

### ISSUE THREAD

**Issue by jpike88** [rFlex/SCRecorder#206]

**Comment by jpike88** [comment]
Is the owner even on this? Look at all the issues and pull requests. Looks like its been abandoned.

**Comment by MMasterson** [comment]
@jpike88 it's good starting off point. looks like some issues were just never closed, and it does seem neglected for updates. fork it and fix it up to your liking, that's what I did. I've been using and messing around with the framework for sometime.

**Comment by rFlex** [comment]
@jpike88 You are very welcome to solve the issues yourself or create your own camera framework if you feel adventurous enough. As a reminder I'm providing this software for free, this is written on my free time. Not sure how you can complain about something you get for free, especially considering the amount of work that have been done here.

I have unfortunately been extremely busy for the past few months and can't spend time maintaining it. I would love that someone starts helping me out with the project in the meantime.

**Comment by MMasterson** [comment]
@Rflex +1

**Comment by StormFactory** [comment]
Totally agree with @rFlex!

**Comment by r3trosteve** [comment]
What right do you have to make these types of comments? This type of thing really annoys me. There is no obligation to provide you anything, be grateful and contribute, if you can.

**Comment by yarikpwnzer** [comment]
Thousands of our clients use this video recording SDK every day, maybe it has some bugs, but it's very stable and free.

**Comment by twomedia** [comment]
@rFlex I agree with you mate, I haven't been using this library long but I have come across a few issues which I have submitted but in no way do I expect you to review/solve them. You have a life, a job at Vine, that comes first! I'll do my best to contribute what I can :+1:

**Comment by benjaminhorner** [comment]
@Rflex +1

**Comment by olivierlesnicki** [comment]
Let's close this issue already.
