### ISSUE TITLE
Handling permission denial to camera and microphone

### ISSUE THREAD

**Issue by praveenaj** [rFlex/SCRecorder#240]
If the user denies access to camera and microphone when the app is launched for the first time, the app enters a limbo state.

Is there a way to detect if user granted/denied access?

**Comment by benjaminhorner** [comment]
This is not an SCRecorder feature. You should detect that prior to opening the View that is using the Recorder. Check this SO answer: http://stackoverflow.com/questions/20464631/detect-permission-of-camera-in-ios

**Comment by praveenaj** [comment]
Thanks for the clarification!
