### ISSUE TITLE
SCRecorderExamples don't save video with audio

### ISSUE THREAD

**Issue by JoseMendesGouveia** [rFlex/SCRecorder#249]
I tested the ObjC example of the SCRecorderExamples, using an iPhone 5c with iOS9.1. I noticed when saving video only the first 3 seconds of audio are recorded. The video is completely recorded but the audio is only recorded during the first three seconds. I tested several times, searched for a maximum audio time record and searched in the SCRecorder issues, but with no avail.

This behaviour has been detected before? There is any configuration to limit the time of audio recording in the video? Or is this a bug?

Best regards.

**Comment by JoseMendesGouveia** [comment]
I have noticed also that it only records audio in the first 3 seconds of each segment. If I have a video with 3 segments, I will have audio in the beginning of each segment.
Any thoughts about this behaviour?

**Comment by JoseMendesGouveia** [comment]
Another note:
This only happens when it uses fastRecordMethodEnable is false, so instead of using AVCaptureMovieFileOutput it uses AVCaptureVideoDataOutput and AVCaptureAudioDataOutput.
With fastRecordMethodEnable set to YES the file is correctly recorded with audio and video but the SCVideoPlayerViewController cannot read the video because the recordSession assetWriter, videoInput and audioInput are nil, and SCPlayer cannot reproduce it, but the filters are applied, visible after exporting the video file.

**Comment by JoseMendesGouveia** [comment]
I found another thread with the same error: issue #118.
I believe I found the cause of the problem, the delegate captureOutput didOutputSampleBuffer stops receiving audio output but continues receiving video output. Noticed also that it only receives 125 times the audio output, and the amount of times accounts for aprox. 2.8 - 2.9 seconds. 
@rFlex Do you have any idea why this is happening?

**Comment by LiweiDong** [comment]
Same problem on iPhone 6s Plus ! Do you have any other solutions ?

**Comment by JoseMendesGouveia** [comment]
I have found an work around. There could be a better away, but it works correctly. The error is originated in CMSampleBufferCreateCopyWithNewTiming and it interferes with AVAudio delegate. The solution is to comment out CMSampleBufferCreateCopyWithNewTiming:

- (CMSampleBufferRef)adjustBuffer:
...
    CMSampleBufferRef sout = sample;
    //CMSampleBufferCreateCopyWithNewTiming(nil, sample, count, pInfo, &sout);


HTH.
If someone has a better approach to this problem, please share it.

**Comment by zhengwu119** [comment]
Try this:
http://stackoverflow.com/questions/26768987/avcapturesession-audio-doesnt-work-for-long-videos
Works for me!

**Comment by LiweiDong** [comment]
@JoseMendesGouveia way to solve my problem !
thanks a lot

**Comment by mitchellporter** [comment]
The solution provided by @JoseMendesGouveia works. Here's the entire method formatted properly: 
```Objective-C
- (CMSampleBufferRef)adjustBuffer:(CMSampleBufferRef)sample withTimeOffset:(CMTime)offset andDuration:(CMTime)duration {
    CMItemCount count;
    CMSampleBufferGetSampleTimingInfoArray(sample, 0, nil, &count);
    CMSampleTimingInfo *pInfo = malloc(sizeof(CMSampleTimingInfo) * count);
    CMSampleBufferGetSampleTimingInfoArray(sample, count, pInfo, &count);
    
    for (CMItemCount i = 0; i < count; i++) {
        pInfo[i].decodeTimeStamp = CMTimeSubtract(pInfo[i].decodeTimeStamp, offset);
        pInfo[i].presentationTimeStamp = CMTimeSubtract(pInfo[i].presentationTimeStamp, offset);
        pInfo[i].duration = duration;
    }
    
    CMSampleBufferRef sout = sample;
//    CMSampleBufferCreateCopyWithNewTiming(nil, sample, count, pInfo, &sout);
    free(pInfo);
    return sout;
}
```

**Comment by crsantos** [comment]
@rFlex Any ideas about this?

**Comment by mitchellporter** [comment]
@crsantos Looking forward to @rFlex's response. Although removing the line in my comment above fixes the issue, I'm not sure if it will cause problems elsewhere as I haven't been working with SCRecorder long enough.
