### ISSUE TITLE
Newbie Question : How to import local video ( mp4 file ) to make SCRecordSession

### ISSUE THREAD

**Issue by lemanhtien** [rFlex/SCRecorder#264]
I have some videos and want to merge video and customize by SCRecord. I know that i should make SCRecordSessionSegment for ech video and then make SCRecordSession from all segments.
But i dont know how to make segment and then make session :(
Thanks for helping me ;)

**Comment by lfarah** [comment]
@lemanhtien can you post your code here? I'm having the same problem

**Comment by lemanhtien** [comment]
@lfarah hey bro, try this. Its too long for me to remember, but i remembered that i got problem because i didn't set file type for SCRecordSession

```
SCRecordSession *recordSession = [SCRecordSession recordSession];

// Create record segment for each video
SCRecordSessionSegment *record = [[SCRecordSessionSegment alloc] initWithURL:[NSURL fileURLWithPath:filePath] info:nil];

[recordSession addSegment:record]
[recordSession setRecorder:[SCRecorder recorder]];
[recordSession setFileExtension:@"mp4"];
[recordSession setFileType:AVFileTypeMPEG4];

```

**Comment by lfarah** [comment]
Thanks, @lemanhtien. You're awesome! 🎉🎉🎉
