### ISSUE TITLE
SCPlayer's setItemByStringPath does not work

### ISSUE THREAD

**Issue by mitchellporter** [rFlex/SCRecorder#271]
I have a local video file and when I retrieve it's file path, it's successfully located and not nil. However, whenever I try to setup the player using `setItemByStringPath`, no playback happens.

If I try using `setItemByUrl`, and just create the URL using the same file path, the player will play the video.

Doesn't work:
```Swift
let filePath = NSBundle.mainBundle().pathForResource("iqsypmnomnldszsd7lov", ofType: "mp4")
player.setItemByStringPath(filePath)
```
Does work:
```Swift
let filePath = NSBundle.mainBundle().pathForResource("iqsypmnomnldszsd7lov", ofType: "mp4")
player.setItemByUrl(NSURL(fileURLWithPath: filePath!))
```

**Comment by rFlex** [comment]
The API may be confusing, but it's actually just doing NSURL(string: inputString) under the hood. pathForResource will return a file path (e.g "/Users/mitchell/vacation.mp4"), but setItemByStringPath asks for an absolute string representation of an URL (e.g "file:///Users/mitchell/vacation.mp4").

**Comment by mitchellporter** [comment]
Thanks for the clarification Simon!
