### ISSUE TITLE
Processing an image from Camera/Library with SCFilter results in rotated image

### ISSUE THREAD

**Issue by luigidimuzio** [rFlex/SCRecorder#272]
I am using scfilters for an instagram-like app
I have generated a couple of filters with CoreImageShop, they look good but when I use the **UIImageByProcessingUIImage** to get an uiimage and I set it to an uiimageview it appears rotated

```
let cisfURL = NSBundle.mainBundle().URLForResource(filterName, withExtension: "cisf")
let restoredFilter = SCFilter(contentsOfURL: cisfURL)
if let filteredImage = restoredFilter.UIImageByProcessingUIImage(image) {
    return filteredImage
}
```

Is there something i'm doing wrong?
thank you

**Comment by rFlex** [comment]
Should be fixed. Can you check if that works?
