### ISSUE TITLE
Slow shutter sound

### ISSUE THREAD

**Issue by sherm4n90** [rFlex/SCRecorder#285]
I'm having an weird issue with the shutter sound when taking a picture. Sometimes the shutter make like a pause at middle and then finish the sound, sometimes the pause is shorter, but it never is as fast as the native camera shutter sound. Thanks in advance.

**Comment by MMasterson** [comment]
@sherm4n90 sounds like something is a blocking the thread. A debug tip is to pause the application in the middle of the capturing and inspect the threads.

**Comment by sherm4n90** [comment]
@MMasterson Thks, I will take a look and let you know.

**Comment by levantAJ** [comment]
Thank you :) 

Thanks & Best Regards,

Le Tai
Mobile Software Engineer 
Mobile: +84 90 360 91 21 
Email: sirlevantai@gmail.com
Skype: sirlevantai

**Comment by sherm4n90** [comment]
@MMasterson Solved! was the [recorder stopRunning] in the viewWillDisappear method. Thanks
