### ISSUE TITLE
Setting SCImageView on Player stops playback.

### ISSUE THREAD

**Issue by MMasterson** [rFlex/SCRecorder#286]
I've been trying to implement filters, but I am having several issues. The code below _should_ work, but there is 0 playback.

```
    [_playerView setFrame:[[self containerView ] bounds]];
    [[ _playerView player] setItemByAsset:[[self recordSession] assetRepresentingSegments]];
    [[ _playerView playerLayer] setFrame:[[self containerView ] bounds]];
    [[ _playerView playerLayer] setVideoGravity:AVLayerVideoGravityResizeAspectFill];
    
    [[ _playerView player] setDelegate:self];
    [[ _playerView player] setLoopEnabled:YES];
    [[ _playerView player] beginSendingPlayMessages];

    [[ _playerView player] play];

    SCFilterImageView *filterView = [[SCFilterImageView alloc] initWithFrame:[[self containerView ] bounds]];
    filterView.filter = [SCFilter filterWithCIFilterName:@"CIPhotoEffectInstant"];
 [[_playerView player] setSCImageView:filterView];



```

when I remove
`
    [[_playerView player] setSCImageView:filterView];`

The video plays...

Anyone have any luck on gettings Filters working with SCRecorder?

**Comment by MMasterson** [comment]
I've added
`    [_playerView insertSubview:filterView belowSubview:_playerControlsView];`

and moved

`    [[ _playerView player] setItemByAsset:[[self recordSession] assetRepresentingSegments]];`

and it is not working intermittently. Takes a few times to get the video to actually play through the filter.

The end goal is to use the Swipe View but I've had 0 luck with that.

_ iOS9_

**Comment by shiweige** [comment]
@MMasterson Maybe I met the same problem, could you please describe what is _playerView and _playerControlsView in your code?

**Comment by MMasterson** [comment]
sure @shiweige  

_playerView is an outlet of SCVideoPlayerView on the story board and _playerControlsView is a UIView that holds the play button, next and cancel button for the camera.

**Comment by sherm4n90** [comment]
@MMasterson you don;t need the SCplayerView since your renderer will be the SCFilterImageView or your future SwipeableFilterVIew. 
First, initialize your scPlayer.
```
self.scPlayer.shouldSuppressPlayerRendering = NO;
[self setupFilterSwitcher];
self.scPlayer.SCImageView = self.swipeableFilterView
```;

Then
```
- (void)setupFilterSwitcher {
 self.swipeableFilterView.filters = <your filters>;
 self.swipeableFilterView.delegate = self; //If you need it
 self.swipeableFilterView.contentMode = UIViewContentModeScaleAspectFit; //or whatever
}
```

my self.swipeableFilterView is an outlet from my storyboard.
That should do it.

**Comment by MMasterson** [comment]
@sherm4n90 I've made the appropriate changes

Changed my SCplayerView to a SCSwipeableFilterView and reconnected it as an outlet named swipeableFilterView

in my viewDidLoad
I've added 

```
  if(_player == nil){
        _player = [[SCPlayer alloc] init];
    }
```
I've added your method

```
- (void)setupFilterSwitcher {
    self.swipeableFilterView.filters = @[[SCFilter filterWithCIFilterName:@"CIPhotoEffectNoir"],
                                         [SCFilter filterWithCIFilterName:@"CIPhotoEffectChrome"],
                                         [SCFilter filterWithCIFilterName:@"CIPhotoEffectInstant"],
                                         [SCFilter filterWithCIFilterName:@"CIPhotoEffectTonal"],
                                         [SCFilter filterWithCIFilterName:@"CIPhotoEffectFade"]];
    self.swipeableFilterView.delegate = self;
    //If you need it
    self.swipeableFilterView.contentMode = UIViewContentModeScaleAspectFit; //or whatever
}

```

in my viewDidAppear
I've added 
```
    _player.shouldSuppressPlayerRendering = NO;
    [self setupFilterSwitcher];
    _player.SCImageView = self.swipeableFilterView;
```

and it does play the video although, the swipe does not work - as in the filters do not change

**Comment by sherm4n90** [comment]
@MMasterson did you try the - (void)swipeableFilterView:(SCSwipeableFilterView *__nonnull)swipeableFilterView didScrollToFilter:(SCFilter *__nullable)filter protocol method? This will tell you if the scrolling through filters is working.

**Comment by MMasterson** [comment]
@sherm4n90 - It is **not** being called - but can't seem to figure out why.

Is there a User Interaction field I have to enabled programmatically?

**Comment by MMasterson** [comment]
@sherm4n90 even with your edit, no luck on getting the gesture to fire.

**Comment by sherm4n90** [comment]
@MMasterson mm, nothing to add, maybe you have some view covering the swipeableView.

**Comment by MMasterson** [comment]
@sherm4n90 yup.. just double checked, had a view over the swipeView.

Thank's so much for your help with the set up!

**Comment by sherm4n90** [comment]
@MMasterson great! glad to help
