### ISSUE TITLE
AVAssetWriter - Could not be decoded on this device

### ISSUE THREAD

**Issue by ayurkows** [rFlex/SCRecorder#300]
Error Domain=AVFoundationErrorDomain Code=-11855 "Cannot Decode" UserInfo={NSUnderlyingError=0x157372050 {Error Domain=NSOSStatusErrorDomain Code=560226676 "(null)"}, NSLocalizedFailureReason=The media data could not be decoded on this device., NSLocalizedDescription=Cannot Decode}

Getting the above error when the writer tries to start writing. This only occurs on iphone 5s, and only occurs sometimes. The most reproducible case is when we move from a VC with an AVPlayer that is playing media straight to the VC that handles the recording. The same VC with the recorder works correctly with the same settings when not navigating from the VC with the AVPlayer. What can cause this error and where can I look to fix this?

**Comment by mitchellporter** [comment]
@ayurkows How did you solve this issue?

**Comment by ayurkows** [comment]
For some reason the sample rate was being changed, making it incompatible with the 5s. We hard coded in the sample rate in the pod to make sure it was always correct. We might look further into it later if we find the time.

**Comment by priyeshmarvi** [comment]
@ayurkows I can't understand how did you do that??? can you please give  some more info.?
