### ISSUE TITLE
Continuous Exposure/white balanace doesn't seem to work well

### ISSUE THREAD

**Issue by cerupcat** [rFlex/SCRecorder#301]
When testing exposure using SCRecorder vs the build in iOS video app, SCRecorder can take upwards of 10-20 seconds to get a AVCaptureDeviceSubjectAreaDidChangeNotification changed event which updates the focus/exposure. On the build in iOS video app it's almost instance. Any ideas what the issue could be?

I'm testing by putting a black piece of paper up to the camera and then removing and seeing how long it takes for the camera to adjust.

**Comment by rFlex** [comment]
Hey,

Is it related to your pull request at https://github.com/rFlex/SCRecorder/pull/302 ?

**Comment by cerupcat** [comment]
Yeah, fixed in the pull request. :)
