### ISSUE TITLE
A arguement to remove this lib from Github

### ISSUE THREAD

**Issue by andyrexford** [rFlex/SCRecorder#303]
Im fairly certain that this lib alone has propelled the overwhelming amount of video apps in the market, if you now work at vine and are no longer updating it or answering q's might as well take it a step further and take this library down so only the ppl who put in the work can create these types of apps.

**Comment by mitchellporter** [comment]
I don't follow any of your logic.. your argument really doesn't make any sense and I couldn't disagree with it any more. I'd be amazed if Simon would actually remove this from Github.

**Comment by guodong000** [comment]
good suggestion... 😂😂

**Comment by joeyslack** [comment]
This is an invalid issue. Should be closed without comment.
