### ISSUE TITLE
Cannot get watermarking to work

### ISSUE THREAD

**Issue by jln19** [rFlex/SCRecorder#306]
Couldn't find any documentation or a working example of watermarking videos. The below is what I could piece together. Can you tell me what is wrong with this? The video gets exported, but the watermark never appears. The watermark is a valid .png file (my_watermark@2x.png) in the app bundle.

```
AVAsset *asset = self.recordSession.assetRepresentingSegments;
    NSURL *tempUrl = [NSURL fileURLWithPath:[NSTemporaryDirectory() stringByAppendingPathComponent:@"videomarked.mov"]];
    
    SCAssetExportSession *assetExportSession = [[SCAssetExportSession alloc] initWithAsset:asset];
    assetExportSession.outputUrl = tempUrl;
    assetExportSession.outputFileType = AVFileTypeMPEG4;
    assetExportSession.videoConfiguration.preset = SCPresetMediumQuality;
    assetExportSession.videoConfiguration.watermarkImage = [UIImage imageNamed:@"my_watermark"];
    assetExportSession.videoConfiguration.watermarkFrame = CGRectMake(0, 0, 320, 480);
    [assetExportSession exportAsynchronouslyWithCompletionHandler: ^{
        if (assetExportSession.error == nil) {
            // I get success here, but the video does not have a watermark
            
        } else {
            // Something bad happened
            
        }
    }];
```

I've confirmed that `generatedWatermarkImage` is valid in `SCAssetExportSession:_buildWatermarkFilterForVideoSize`

**Comment by jln19** [comment]
I've confirmed that `generatedWatermarkImage` is valid in `_buildWatermarkFilterForVideoSize`

**Comment by rFlex** [comment]
Do you have a small project that you can share so I can investigate? That would be so awesome :)

**Comment by jln19** [comment]
I will try to whip one up. In the meantime though can you confirm that watermarking has worked for you?

**Comment by jln19** [comment]
Here is the simple project showing that watermarking doesn't work. Thanks for investigating :)

[SCRecorderWatermarkTest.zip](https://github.com/rFlex/SCRecorder/files/260428/SCRecorderWatermarkTest.zip)

**Comment by Klucherev** [comment]
@rFlex Hi! I think problem is in - (SCFilter *)_generateRenderingFilterForVideoSize:(CGSize)videoSize method. 
`    if (renderingFilter.isEmpty) {
        renderingFilter = nil;
    }
`
alway returns nil

**Comment by rFlex** [comment]
Thanks a lot for the help!. @Klucherev yeah good call, that was what the problem was :).

**Comment by jln19** [comment]
@rFlex I tried making this update. Now there is a crash at line 317 of SCFilter.m. -[CIImage imageByCompositingOverImage:]: unrecognized selector sent to instance 0x14648c40

**Comment by rFlex** [comment]
Are you running on iOS 7?

**Comment by jln19** [comment]
Yes, that device was iOS7. I tested again on iOS9 and didn't get the crash, which makes sense. However, why does adding the watermark change the orientation of the video?
![before](https://cloud.githubusercontent.com/assets/713741/15296587/d839e3c6-1b4a-11e6-83f3-0cb6968f2da7.PNG)
![after](https://cloud.githubusercontent.com/assets/713741/15296591/da5b4262-1b4a-11e6-8790-430f3204ff66.PNG)

**Comment by rFlex** [comment]
This is another issue where your input video has a orientation metadata that isn't being respected by SCRecorder. You may be able to fix that by setting keepInputAffineTransform to false in SCVideoConfiguration

**Comment by jln19** [comment]
`assetExportSession.videoConfiguration.keepInputAffineTransform = NO;`

results in this:

![img_7943](https://cloud.githubusercontent.com/assets/713741/15296999/d1246ad2-1b4c-11e6-9ea3-2203369c1de8.PNG)

This is the desired result:
![desired](https://cloud.githubusercontent.com/assets/713741/15297026/f0a5c180-1b4c-11e6-9c4f-08efeff9a3cd.jpg)

**Comment by rFlex** [comment]
Ok, I will check it out some time today

**Comment by jln19** [comment]
@rFlex any updates on this? I've invested a lot of time implementing SCRecorder as a solution to our video recording/playback needs but if watermarking doesn't work I can't use it... and explain to my company why I have to start over :(

**Comment by rFlex** [comment]
[SCRecorderWatermarkTest 3.zip](https://github.com/rFlex/SCRecorder/files/271087/SCRecorderWatermarkTest.3.zip)

Here is a working example based of your project.

**Comment by jln19** [comment]
Thanks. What did you change? ViewController.m looks the same. Did you make changes in the SCRecorder files?

**Comment by rFlex** [comment]
I added a videoComposition that will take care of transforming your video so the output video doesn't have any special rotation metadata.

**Comment by jln19** [comment]
I see. Thank you.

**Comment by HackShitUp** [comment]
@rFlex I have the same question regarding overlays but I can't save the video with the UIView overlay in it. Here's a reference to the issue I posted:

https://github.com/rFlex/SCRecorder/issues/414

**Comment by UlanNurmatov** [comment]
**It seems that I can't add watermark without adding a filter. How do I add a watermark without using a filter?** 

Here's my code: 
```
guard self.asset != nil else { return }
            let assetExportSession = SCAssetExportSession.init(asset: self.asset)
            assetExportSession.delegate = self
            assetExportSession.inputAsset = self.asset
            assetExportSession.contextType = SCContextType.auto
            assetExportSession.outputUrl = self.recordSession.outputUrl
            assetExportSession.outputFileType = AVFileType.mp4.rawValue
            assetExportSession.videoConfiguration.filter = SCFilter.init(ciFilterName: "CIPhotoEffectFade")
            assetExportSession.videoConfiguration.watermarkImage = UIImage(named: "twitter")
            assetExportSession.videoConfiguration.watermarkFrame = CGRect(x: 0, y: 0, width: 200, height: 40)
            assetExportSession.videoConfiguration.preset = SCPresetHighestQuality
            assetExportSession.exportAsynchronously {
                if assetExportSession.error == nil {
                    self.saveVideo(withURL: assetExportSession.outputUrl!)
                }
            }
```
