### ISSUE TITLE
Video orientation wrong with SCSwipeableFilterView

### ISSUE THREAD

**Issue by Bragegs** [rFlex/SCRecorder#307]
Hey! Trying to show video from imagepicker with SCSwipeableFilterView in a portrait only app.

**imagePicker:**
![image](https://cloud.githubusercontent.com/assets/10655264/15276506/59780b5e-1aea-11e6-9a79-ca71071840a5.png)

Initiating SCRecorder with these two:
`
        recorder.autoSetVideoOrientation = false;
        recorder.videoOrientation = AVCaptureVideoOrientation.Portrait;
`

Getting video from imagepicker
`                   
                    //VideoURL from imagePicker;
                    let segment = SCRecordSessionSegment(URL: videoURL, info: nil);
                    self.session.addSegment(segment);
`
Showing video with this code with scplayer and scswipeablefilterview

`        let videoAsset = segment.asset;
        player.setSmoothLoopItemByAsset(videoAsset, smoothLoopCount: 5);
`

**SCPlayer with SCSwipeableView:**
![image](https://cloud.githubusercontent.com/assets/10655264/15276508/64ac1c90-1aea-11e6-8975-319e65f353a1.png)

printing the asset video orientation gives me uilandscaperight, it is saved from snapchat. Anyone knows what I am doing wrong? (And does anyone have experience in rotating avassets?)

**Comment by mitchellporter** [comment]
@Bragegs If the issue was closed because you solved the problem, then you should post a quick solution so that in the future other devs can save time.

**Comment by Bragegs** [comment]
Instead of needing to have the right orientation when the view appears, I added functionality to rotate the video if the user wants to. Made a document on how I did it. Feel free to improve

[Note on rotating and exporting ](https://notehub.org/2ekcn)

**Comment by khush004** [comment]
@Bragegs  Can you please provide solution? as I am facing the same issue.
