### ISSUE TITLE
Flickering when playing saved video

### ISSUE THREAD

**Issue by bughana** [rFlex/SCRecorder#337]
Hi there,

firstly thanks for the great library.
I have a problem with flickering in recorded videos. Here is what i do:
- I record a video with different segments and save each of the segments to the documents directory
- afterwards I merge all segments using AVAssetExportSession and save the resulting video in the cam roll
- when i play the video afterwards, it flickers from time to time. It looks like there is one frame shown in between the video
 (i attached a video to show what i mean, flickers once close to the end. Sorry, for all the movement in the video, as the flickering does not always happen, i had to take a video that is short enough and actually captures it)

![flickering](https://cloud.githubusercontent.com/assets/1824097/17478821/bebd8c3e-5d6e-11e6-8bd9-903994c90cb4.gif)

Did anybody face this issue as well and has probably an idea how to solve it?

Help would be much appreciated, thanks in advance

**Comment by amilham** [comment]
Are you using the same SCFilter for playback and for exporting simultaneously?

**Comment by bughana** [comment]
Hm... I use the selectedFilter of the SCSwipeableFilterView (which is set as the SCImageView of the player) as the filter in the videoConfiguration of the exportSession. So yes, this is the same filter and yes, the video is playing in a loop while saving the video file. Is that a problem?

**Comment by amilham** [comment]
Yes. Make a copy of it for the export session instead.

**Comment by bughana** [comment]
Thanks so much, that fixed the problem 👍
