### ISSUE TITLE
Video, audio not getting recorded during interruption like Skype call.

### ISSUE THREAD

**Issue by arunkp1991** [rFlex/SCRecorder#38]
Receive call or call from the device through Skype. Now open the application (SCRecorderExamples) and begin recording. Seems like, first segment recorded successfully but it isn't. Can not record again. Navigate to preview, no video will be shown. Delegate methods, recorder:didAppendVideoSampleBuffer: & recorder:didAppendAudioSampleBuffer: are not getting called.

If Skype calls arrives while recording, we can continue recording but there will not be any sound for the  video while playing on preview view.

While putting breakpoints here and there I got these two errors. 

ERROR:     [0x103534000] AVAudioSessionPortImpl.mm:50: ValidateRequiredFields: Unknown selected data source for Port iPhone Microphone (type: MicrophoneBuiltIn)

End record segment -1, error : Error Domain=AVFoundationErrorDomain Code=-11821 "Cannot Decode" UserInfo=0x178271240 {NSUnderlyingError=0x17824b1f0 "The operation couldn’t be completed. (OSStatus error 560226676.)", NSLocalizedFailureReason=The media data could not be decoded. It may be damaged., NSLocalizedDescription=Cannot Decode}

Problems is in iOS7. When you set audioEnabled property of SCRecorder to NO, works perfectly but without sound.

Please look into this issue.

**Comment by BhavinBhadani** [comment]
I have a same issue while phone call...my capture session stuck and do not record anything. Is there any solution for this??

**Comment by priyeshmarvi** [comment]
@rFlex same problem ... but nothing solved for me
