### ISSUE TITLE
CaptureSessionPreset with different devices

### ISSUE THREAD

**Issue by Providnuk** [rFlex/SCRecorder#382]
@rFlex I want to get the highest quality video. If I change device during recording(front/back) during recording, should I change CaptureSessionPreset? 
How else can I improve video quality?

**Comment by rFlex** [comment]
If you set the capture session preset to High you should have the highest quality possible for both output devices. You can also configure the bitrate in videoConfiguration to the highest possible value you think will be reasonable for your use case. Keep in mind that the rear and front camera might have a different image size.

**Comment by Providnuk** [comment]
Thanks @rFlex !
