### ISSUE TITLE
How can i get the priority of camera?

### ISSUE THREAD

**Issue by charleschwang** [rFlex/SCRecorder#386]
Some apps like FaceTime should take away the right to use of camera when my SCRecorder was recording，then i can not start recording again.But if i set "recorder.audioConfiguration.shouldIgnore = YES"，it works well.What should i do?
Thanks a lot.

errors:
Began record segment: Error Domain=AVFoundationErrorDomain Code=-11861 "无法编码媒体"(cannot decode) UserInfo={NSUnderlyingError=0x106b13470 {Error Domain=NSOSStatusErrorDomain Code=-12651 "(null)"}, NSLocalizedFailureReason=编码参数不受支持(unsupported decode parameter)。, NSLocalizedDescription=无法编码媒体(can not decode)}

**Comment by charleschwang** [comment]
if i set recorder.audioConfiguration.shouldIgnore = YES，it works well

**Comment by StormFactory** [comment]
@charleschwang You're closing the issue.  Please leave the result of what you found out in case others have similar issues.  Thanks.
