### ISSUE TITLE
Segment which follow immediately after pause / record have a glitch - delay (missing frames)

### ISSUE THREAD

**Issue by peterpaulis** [rFlex/SCRecorder#390]
I want to add support for continuous recording, to keep the let's say last 20 seconds... i tried pausing and resuming, creating several segments and then deleting the old one, however, there is a glitch when i stop recording and start a new segment

i even do the record / pause on the same thread as the session queue

```
- (void)onTimer:(NSTimer *)timer {
    
    dispatch_async(self.recorder.sessionQueue, ^{
    
        [self.recorder pause:^{
        
        }];
        
        [self.recorder record];
        
    });
    
}
```

so it looks like some buffers are lost, but how to avoid that?

**Comment by Avatarchik** [comment]
Hi! it turned out decides?

**Comment by peterpaulis** [comment]
i had to build my own separate solution... due to thread issues etc. it was not possible to make this happen, (or modify) with SCRecorder
