### ISSUE TITLE
Error: Remove any record segment that you don't want

### ISSUE THREAD

**Issue by ghost** [rFlex/SCRecorder#45]
Hi,

I follow your guide to remove the record segment like this:

[recordSession removeSegmentAtIndex:1 deleteFile:YES]; 
or
[recordSession removeSegmentAtIndex:1 deleteFile:NO];

I have 2 cases with the error:
1. record 2 segments (open camera, tap and hold 2 times), then remove both 2 segments, continue to record, then convert video --> can't convert
2. record 3 segments (open camera, tap and hold 3 times), then remove the third segment, then record addition 1 segment, then convert video --> video result have 2 segment (the first and the second segment, not have the four segment)

I'm looking forward your help!

Thanks and best regard!

**Comment by fresh83** [comment]
dude...come on this guy has made your life so easy. Press the damn edit button. Dont bother this man with b.s
