### ISSUE TITLE
Filtering video with the method provided in the tutorials doesn't work under iOS 8

### ISSUE THREAD

**Issue by ghost** [rFlex/SCRecorder#72]
I was playing around with your example app, and switched out the SCSwipeableFilterView called filterSwitcherView for a SCVideoPlayerView. Playing unfiltered videos in it works fine, but when I try to add a filter like the way shown in the tutorial: 

```
- (void)viewDidLoad
{
    [super viewDidLoad];

    self.filterSwitcherView.contentMode = UIViewContentModeScaleAspectFit;



    self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"Save" style:UIBarButtonItemStyleBordered target:self action:@selector(saveToCameraRoll)];


    self.filterSwitcherView.player.loopEnabled = YES;
}

- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];

    [self.filterSwitcherView.player setItemByAsset:_recordSession.assetRepresentingRecordSegments];

    [self.filterSwitcherView.player play];

    SCImageView *ImageView = [SCImageView new];

    ImageView.filterGroup = [SCFilterGroup filterGroupWithFilter:[SCFilter filterWithName:@"CIPhotoEffectNoir"]];
    ImageView.frame = self.view.bounds;
    [self.view addSubview:ImageView];
    self.filterSwitcherView.player.CIImageRenderer = ImageView;
}
```

I get a black screen where the movie should be playing. This is running on an iPhone 5 with iOS 8. It seems to run fine on another phone with iOS 7.  Without any modifications the filters included with the app are working with the SCSwipeableFilterView, but I wasn't able to figure out where the filters actually get applied in the code, what with it being spread across a bunch of files and having the OpenGL stuff. 

Thanks for putting this awesome library together, it provides good examples of a lot of stuff I was trying to learn.

**Comment by razan1994alali** [comment]
hey, i'm getting the black screen and cannot find SCImageViewEnabled to set it true. any help?
