### ISSUE TITLE
Orientation issue when switching cameras

### ISSUE THREAD

**Issue by nchrys** [rFlex/SCRecorder#79]
Hi,
I am using SCRecorder with
autoSetVideoOrientation = YES,
initializeRecordSessionLazily = NO 
shouldTrackRecordSegments = NO.
I used this last option because setting to YES caused quite some bugs on my iPhone 4S.

So I noticed that when I take multiple segments in a video, with the first segment from the back camera and the second segment on the front camera then the segment from the front camera is recorded with a wrong orientation, it is rotated 90°...
Thank you in advance if you have a solution!

**Comment by khush004** [comment]
@fjcaetano I am facing the same issue and have used this [https://github.com/rFlex/SCRecorder/commit/4b2a3b0be70a31d34f1d099e985c5307b0684730](url) URL to solve my problem but it doesn't works for me, Can you please help me?

**Note:** 
https://github.com/fjcaetano/SCRecorder
This fork is also mirrioring 

![screen shot 2019-01-19 at 11 51 27 am](https://user-images.githubusercontent.com/29862624/51423116-9781c800-1be0-11e9-9cea-c262c244ba5e.png)
