### ISSUE TITLE
AVAssetWriterInput error when saving to device using SVAssetExportSession

### ISSUE THREAD

**Issue by jp-src** [rFlex/SCRecorder#80]
First of all, thank you considerably for this library, including the Xamarin bindings ;)

I am basically trying to reproduce parts of the examples you have provided in Xamarin.iOS.
However, I get an error when trying to save a video with a filter to my library.

I get the following error when using the ExportAsynchronously method of the export session:

```
MonoTouch.Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: *** -[AVAssetWriterInput requestMediaDataWhenReadyOnQueue:usingBlock:] Cannot call method when status is 0
```

Any help would be greatly appreciated.

**Comment by onmyway133** [comment]
This is the docs on `AVAssetWriterInput` `convenience init(mediaType mediaType: String, outputSettings outputSettings: [String : AnyObject]?)`

> This is useful if, for example, you are appending buffers that are already in a desirable compressed format.  However, if not writing to a QuickTime Movie file (i.e. the AVAssetWriter was initialized with a file type other than AVFileTypeQuickTimeMovie), AVAssetWriter only supports passing through a restricted set of media types and subtypes
